{"name": "Проверка входа пользователя c неправильным username", "status": "passed", "steps": [{"name": "Проверка status_code ответа", "status": "passed", "start": 1714322446313, "stop": 1714322446313}], "start": 1714322445661, "stop": 1714322446315, "uuid": "a104fd10-5bf5-444d-8c14-74de68de5337", "historyId": "6c86e5ac3e00e9605ac00095df73a6e0", "testCaseId": "6c86e5ac3e00e9605ac00095df73a6e0", "fullName": "tests.test_user_api.TestUserApi#test_user_login_with_incorrect_username", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_api"}, {"name": "subSuite", "value": "TestUserApi"}, {"name": "host", "value": "d45763e349a4"}, {"name": "thread", "value": "96300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_api"}]}